[auth]
senha_armazenada = "1234"

# Coloque o conteúdo JSON das credenciais aqui
[general.google_sheets_credentials]
type = "service_account"
project_id = "bradock-439712"
private_key_id = "8f2e98738fdc..."
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "bradock@bradock-439712.iam.gserviceaccount.com"
client_id = "..."
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bradock@bradock-439712.iam.gserviceaccount.com"
